

###
# Một test ngăn cách bởi ###
# ref: https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html#create-custom-http-methods
# Route mặc định của server
GET http://localhost:8080/FinancialManagement/api

### Authentication
GET http://localhost:8080/FinancialManagement/api

###
# Kế Toán
GET http://localhost:8080/FinancialManagement/api/accounting/category
###

GET http://localhost:8080/FinancialManagement/api/accounting/record

###

GET http://localhost:8080/FinancialManagement/api/accounting/record/67b5ff8e8332ff332b65f701
###

POST http://localhost:8080/FinancialManagement/api/accounting/record
Content-Type: application/json

{
  "user_id" : "67b5ff8e8332ff332b65f6fe",
  "date":"2025-01-01T22:13:00.100Z",
  "code": "REF123",
  "name": "Giao dịch BDS",
  "description": "Trump Tower",
  "debit": 20.4,
  "credit": 1000000.0,
  "category": "SALE_AND_SERVICES_REVENUE"
}

###
PUT http://localhost:8080/FinancialManagement/api/accounting/record/67b77bdb87394315af5bad37
Content-Type: application/json

{
  "user_id" : "67b5ff8e8332ff332b65f6fe",
  "date":"2022-01-01T22:12:00.100Z",
  "code": "REF123",
  "name": "Giao dịch phương tiện vận tải",
  "description": "Lamborghini Aventador",
  "debit": 200.0,
  "credit": 70.0,
  "category": "SALE_AND_SERVICES_REVENUE"
}

###

GET http://localhost:8080/FinancialManagement/api/accounting/report/67ca60fd7e4409236a0b3872

###

GET http://localhost:8080/FinancialManagement/api/accounting/report
###


POST http://localhost:8080/FinancialManagement/api/accounting/report
Content-Type: application/json

{
  "user_id": "67b5ff8e8332ff332b65f6fe",
  "reportType": "Bao cao loi nhuan",
  "startDate": "2024-01-01T00:00:00.000Z",
  "endDate": "2024-03-31T23:59:59.000Z",
  "date_created": "2024-04-01T12:30:00.000Z",
  "content": []
}

###
PUT http://localhost:8080/FinancialManagement/api/accounting/report/67eb6fc884c06e5b28d13b54
Content-Type: application/json

{
  "user_id": "67b5ff8e8332ff332b65f6fe",
  "reportType": "Bao cao quy 1 nam 2024",
  "startDate": "2024-01-01T00:00:00.000Z",
  "endDate": "2024-03-31T23:59:59.000Z",
  "date_created": "2024-04-01T12:30:00.000Z",
  "content": []
}
###
# Kiểm Toán
POST http://localhost:8080/FinancialManagement/api/audit
Content-Type: application/json

{
  "title": "Annual Financial Audit",
  "userId": "67b5ff8e8332ff332b65f6fe",
  "auditType": "RECORD_INFO",
  "auditDate": "2024-04-01T12:30:00.000Z",
  "result": "ACCEPTED",
  "recordsId": [
    "67b5ff8f8332ff332b65f704",
    "67b5ff8f8332ff332b65f705"
  ]
}
###

GET http://localhost:8080/FinancialManagement/api/audit
###
GET http://localhost:8080/FinancialManagement/api/audit/67c9ea97e4beec2441729276
###
POST http://localhost:8080/FinancialManagement/api/audit
Content-Type: application/json

{
  "title": "Kiem toan lan 1",
  "userId": "67b5ff8e8332ff332b65f6fe",
  "auditType": "CREDIT_AND_DEBIT_MATCHING",
  "auditDate": "2024-04-01T12:30:00.000Z",
  "result": "REJECTED",
  "reportsId": [
    "67c9ea97e4beec2441729276",
    "67c9eaa9e4beec2441729277"
  ]
}
###

DELETE http://localhost:8080/FinancialManagement/api/audit/67ebc21e663a7c1f3d08e00d
###
# Ngân sách

GET http://localhost:8080/FinancialManagement/api/budget/all

###
GET http://localhost:8080/FinancialManagement/api/budget/67b5ff968332ff332b65f751

###
POST http://localhost:8080/FinancialManagement/api/budget/add
Content-Type: application/json

{
  "user_id": "67b5ff8c8332ff332b65f6ee",
  "budget_type": "FOOD",
  "expected_amount": 500000,
  "spent_amount": 250000
}

###
PUT http://localhost:8080/FinancialManagement/api/budget/67b5ff968332ff332b65f751
Content-Type: application/json

{
  "user_id": "67b5ff8c8332ff332b65f6ee",
  "budget_type": "TECHNOLOGY",
  "expected_amount": 600000,
  "spent_amount": 300000
}

###
#Đầu tư

GET http://localhost:8080/FinancialManagement/api/investment/record
###

GET http://localhost:8080/FinancialManagement/api/investment/record/67b5ff988332ff332b65f765

###

POST http://localhost:8080/FinancialManagement/api/investment/record
Content-Type: application/json

{
  "userId": { "$oid": "67b5ff8c8332ff332b65f6ee" },
  "investmentType": "STOCK",
  "investDate": { "$date": "2024-02-01T00:00:00.000Z" },
  "investedAmount": 500000,
  "expectedReturnRate": 2.5
}

###

PUT http://localhost:8080/FinancialManagement/api/investment/record/67b5ff988332ff332b65f765
Content-Type: application/json

{
  "userId": "67b5ff8c8332ff332b65f6ee",
  "investmentType": "REAL_ESTATE",
  "investDate": "2024-01-31T00:00:00.000Z",
  "investedAmount": 800000,
  "expectedReturnRate": 1.85
}
###


