

###
# Một test ngăn cách bởi ###
# ref: https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html#create-custom-http-methods
# Route mặc định của server
GET http://localhost:8080/FinancialManagement/api

### Authentication
GET http://localhost:8080/FinancialManagement/api

###
# Kế Toán
GET http://localhost:8080/FinancialManagement/api/accounting/category
###

GET http://localhost:8080/FinancialManagement/api/accounting/record

###

GET http://localhost:8080/FinancialManagement/api/accounting/record/67b5ff8e8332ff332b65f701
###

POST http://localhost:8080/FinancialManagement/api/accounting/record
Content-Type: application/json

{
  "user_id" : "67b5ff8e8332ff332b65f6fe",
  "date":"2025-01-01T22:13:00.100Z",
  "code": "REF123",
  "name": "Giao dịch BDS",
  "description": "Nhà mặt phố ",
  "debit": 20.4,
  "credit": 9990.0,
  "category": "SALE_AND_SERVICES_REVENUE"
}

###
PUT http://localhost:8080/FinancialManagement/api/accounting/record/67b77bdb87394315af5bad37
Content-Type: application/json

{
  "user_id" : "67b5ff8e8332ff332b65f6fe",
  "date":"12:00:00 01/01/2022",
  "code": "REF123",
  "name": "Giao dịch phương tiện vận tải",
  "description": "Lamborghini Aventador",
  "debit": 200.0,
  "credit": 70.0,
  "category": "SALE_AND_SERVICES_REVENUE"
}

###

GET http://localhost:8080/FinancialManagement/api/accounting/report/67b5ff928332ff332b65f729

###

GET http://localhost:8080/FinancialManagement/api/accounting/report
###


POST http://localhost:8080/FinancialManagement/api/accounting/report
Content-Type: application/json

{
  "user_id": "67b5ff8e8332ff332b65f6fe",
  "report_type": "Báo cáo lợi nhuận",
  "date_created": "12:00:00 01/03/2025",
  "content": [
    {
      "category": "Revenue",
      "amount": 12345.67
    },
    {
      "category": "Expenses",
      "amount": 6789.01
    }
  ]
}
###
# Kiểm Toán

###

###
# Ngân sách

GET http://localhost:8080/FinancialManagement/api/budget/all

###
GET http://localhost:8080/FinancialManagement/api/budget/67b5ff968332ff332b65f751

###
POST http://localhost:8080/FinancialManagement/api/budget/add
Content-Type: application/json

{
  "user_id": "67b5ff8c8332ff332b65f6ee",
  "budget_type": "FOOD",
  "expected_amount": 500000,
  "spent_amount": 250000
}

###
PUT http://localhost:8080/FinancialManagement/api/budget/67b5ff968332ff332b65f751
Content-Type: application/json

{
  "user_id": "67b5ff8c8332ff332b65f6ee",
  "budget_type": "TECHNOLOGY",
  "expected_amount": 600000,
  "spent_amount": 300000
}

###
#Đầu tư

GET http://localhost:8080/FinancialManagement/api/investment/record
###

GET http://localhost:8080/FinancialManagement/api/investment/record/67b5ff988332ff332b65f765

###

POST http://localhost:8080/FinancialManagement/api/investment/record
Content-Type: application/json

{
  "userId": { "$oid": "67b5ff8c8332ff332b65f6ee" },
  "investmentType": "STOCK",
  "investDate": { "$date": "2024-02-01T00:00:00.000Z" },
  "investedAmount": 500000,
  "expectedReturnRate": 2.5
}

###

PUT http://localhost:8080/FinancialManagement/api/investment/record/67b5ff988332ff332b65f765
Content-Type: application/json

{
  "userId": "67b5ff8c8332ff332b65f6ee",
  "investmentType": "REAL_ESTATE",
  "investDate": "2024-01-31T00:00:00.000Z",
  "investedAmount": 800000,
  "expectedReturnRate": 1.85
}
###


